fix(core, kubevirt): add ability to configure burst for virt-api rate…
deckhouse/virtualization pull request #103
Opened 2024-05-17 08:57 UTC by Isteb4k

… limiter

## Description
When migrating a big number of virtual machines (>50), we encounter a bottleneck in virt-api in the form of a rate limiter that prevents migration completion.

A patch has been updated to virt-api, enabling the configuration of Burst for the rate limiter via an environment variable VIRT_API_RATE_LIMITER_BURST.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [X] Changes were tested in the Kubernetes cluster manually.

2024-05-20 11:26 UTC, fl64 approved these changes

2024-05-20 11:27 UTC, fl64 requested changes

2024-05-20 11:27 UTC, fl64 commented on templates/kubevirt/kubevirt.yaml
> +                    "value": "10"
```suggestion
                    "value": "6000"
```

2024-05-21 11:40 UTC, diafour commented on images/virt-artifact/patches/013-virt-api-rate-limiter.patch
> ++			log.Log.Errorf("failed to parse %s: %s", VirtAPIRateLimiterBurstEnvVar, err)
```suggestion
+			log.Log.Errorf("failed to parse %s: %s, will use default burst %d", VirtAPIRateLimiterBurstEnvVar, err, burst)
```

2024-05-21 11:42 UTC, diafour approved these changes

2024-05-27 10:05 UTC, fl64 approved these changes

2024-05-27 10:13 UTC, merged