Feat/vm/apply new design
deckhouse/virtualization pull request #120
Opened 2024-06-06 12:17 UTC by yaroslavborbat

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-06-24 17:56 UTC, Isteb4k requested changes

2024-06-24 17:56 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vm/internal/cpu.go
> +	if cpuModel != nil && fn(cpuModel, virtv2.FinalizerVMCPUProtection) {
How about using a ProtectionService to protect resources?

2024-06-24 17:56 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vm/internal/ipam.go
> +		//
Empty comment

2024-06-24 17:56 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vm/internal/block_device.go
> +func (h *BlockDeviceHandler) BlockDevicesReady(vm *virtv2.VirtualMachine, s BlockDevicesState) (bool, int) {
Not a public method
Mb rename to сountReadyBlockDevices?

2024-06-24 17:56 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vm/internal/block_device.go
> +func (h *BlockDeviceHandler) updateFinalizers(ctx context.Context, vm *virtv2.VirtualMachine, s BlockDevicesState, fn updaterFinalizer) error {
rename fn variable

2024-06-24 17:56 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go
> +func NewPhaseTransitions(phaseTransitions []virtv2.VirtualMachinePhaseTransitionTimestamp, oldPhase, newPhase virtv2.MachinePhase) PhaseTransitions {
It's hard to understand what's going on here and why it's needed. Let's add a comment?

2024-06-24 17:56 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vm/internal/deletion_handler.go
> +	if logger == nil {
Why do we check the logger for nil but not the client? It seems redundant to check for nil and reassign the logger here. Whichever one is passed, we should use.

2024-06-24 18:04 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/vm/internal/deletion_handler.go
> +	if s.VirtualMachine().IsEmpty() || s.VirtualMachine().Current().GetDeletionTimestamp().IsZero() {
no, we return now if DeletionTimestamp is zero. In the isDeletion func we check the opposite

2024-06-25 13:22 UTC, Isteb4k approved these changes

2024-06-25 14:12 UTC, merged