feat(vm): add statisticHandler
deckhouse/virtualization pull request #206
Opened 2024-07-10 11:30 UTC by yaroslavborbat

## Description
add statisticHandler

## Why do we need it, and what problem does it solve?
We need to display statistics on the virtual machine

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [X] Changes were tested in the Kubernetes cluster manually.

2024-07-11 10:17 UTC, Isteb4k requested changes

2024-07-11 10:17 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vm/vm_reconciler.go
> -			r.logger.Error("The handler failed with an error", slog.String("name", h.Name()), log.SlogErr(err))
Why not error level? It looks like we want to know about it

2024-07-18 14:36 UTC, diafour approved these changes

2024-07-22 11:27 UTC, Isteb4k approved these changes

2024-07-22 11:28 UTC, merged