Feat/sysprep
deckhouse/virtualization pull request #21
Opened 2024-03-06 20:27 UTC by Isteb4k

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-03-12 09:45 UTC, universal-itengineer commented on docs/FAQ_RU.md
> +Предже всего необходимо создать секрет::
```suggestion
Предже всего необходимо создать секрет:
```

2024-03-12 11:47 UTC, yaroslavborbat requested changes

2024-03-12 11:47 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/kvbuilder/kvvm_compare.go
> +		action, err := CompareSysprep(curr, next)
looks like Legacy. Now we don't use CompareKvvm. You should add sysprep to pkg vmchange.

2024-03-13 10:41 UTC, universal-itengineer commented on docs/FAQ_RU.md
> +Прежде всего необходимо создать секрет::
```suggestion
Прежде всего необходимо создать секрет:
```

2024-03-13 15:33 UTC, yaroslavborbat approved these changes

2024-03-14 11:31 UTC, universal-itengineer approved these changes

2024-03-20 09:44 UTC, diafour commented on docs/FAQ.md
> +It's necessary to make sure the virtual machine does not restart, which can be done by setting the run policy as AlwaysOn:
Is it about restart? "AlwaysOn" doesn't prevent restarting from inside the VM.

2024-03-21 09:56 UTC, diafour commented on docs/FAQ.md
> +First of all create sysprep secret:
```suggestion
First, create sysprep secret:
```

2024-03-21 09:57 UTC, diafour commented on docs/FAQ.md
> +And then feel free to create a virtual machine with unattended installation:
```suggestion
Then create a virtual machine with unattended installation:
```

2024-03-21 09:58 UTC, diafour commented on docs/FAQ_RU.md
> +
```suggestion
```

2024-03-21 09:59 UTC, diafour approved these changes

2024-03-21 12:20 UTC, merged