feat(vm-route-forge): add route interface
deckhouse/virtualization pull request #268
Opened 2024-08-09 13:03 UTC by yaroslavborbat

## Description
add route interface

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-08-09 13:50 UTC, Isteb4k requested changes

2024-08-09 13:50 UTC, Isteb4k commented on images/vm-route-forge/internal/netlinkmanager/manager.go
> +	m.cache.Set(vmKey, cache2.Addresses{VMIP: cache2.IP(vmIP), NodeIP: cache2.IP(nodeIP)})
Rename cache2

2024-08-09 13:50 UTC, Isteb4k commented on images/vm-route-forge/internal/controller/route/watch.go
> +	Watch(ctx context.Context) (chan types.NamespacedName, error)
(<-chan types.NamespacedName, error)

2024-08-09 13:50 UTC, Isteb4k commented on images/vm-route-forge/internal/controller/route/ticker.go
> +		tableID:   tableID,
tableID -> routeTableID

2024-08-09 13:50 UTC, Isteb4k commented on images/vm-route-forge/internal/controller/route/ticker.go
> +	routeGet  func(net.IP) ([]netlink.Route, error)
Why store it in the struct's field instead of creating a routeGet() method?

2024-08-09 13:50 UTC, Isteb4k submitted a review, later dismissed

2024-08-09 19:06 UTC, Isteb4k approved these changes

2024-08-10 10:06 UTC, fl64 commented
Need more information on what problem the changes to this PR are solving

2024-08-12 12:18 UTC, merged