test(api): refactor e2e tests
deckhouse/virtualization pull request #280
Opened 2024-08-13 16:42 UTC by hardcoretime

## Description

Add stage 1: apply virtualization resources
Update ginkgo version: 2.20.0
## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-08-14 06:03 UTC, fl64 commented
Please remove all commented lines

2024-08-14 06:03 UTC, fl64 submitted a review, later dismissed

2024-08-14 06:03 UTC, fl64 commented on tests/e2e/testdata/virtualization-resources/vm/base/cfg/cloudinit.yaml
> +      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC9bSJ6RpHDB0jc8oSHk4kgEaoNzv3vNqMhNosLpXYVE6R7CHO3OjOK3eXulVcgiMCRH6EGcDOkMXGM2lvSr5t5HfnqZ1bGxGRCUtMeYs8zDSCMMOuyb57LNjwNAD7cjNhTGvGqFSXqoH5P6lHGIT0M82l
JFY this key must be generated before testing can begin

2024-08-14 07:25 UTC, yaroslavborbat requested changes

2024-08-14 07:26 UTC, yaroslavborbat commented on tests/e2e/kubectl/kubectl.go
> +	namesList := strings.Join(names, " ")
namesList := strings.Join(names, " ")

2024-08-23 10:00 UTC, yaroslavborbat requested changes

2024-08-23 10:00 UTC, yaroslavborbat commented on tests/e2e/config/config.go
> +	res := kubectl.Apply(filePath, kc.ApplyOptions{})
I don't want this

2024-08-23 10:00 UTC, yaroslavborbat commented on tests/e2e/git/git.go
> +
Why do you need this?

2024-08-23 10:31 UTC, yaroslavborbat requested changes

2024-08-23 10:31 UTC, yaroslavborbat commented on tests/e2e/default_config.yaml
> +namespace: "testcases"
rename field namespace

2024-08-26 21:33 UTC, hardcoretime commented on tests/e2e/config/config.go
> +	writeErr := os.WriteFile(filePath, updatedKustomizeFile, 0644)
all files will be copied to /tmp before changing. files in repository will not be changed.

2024-08-26 21:37 UTC, hardcoretime commented on tests/e2e/testdata/virtualization-resources/vm/overlays/custom-ip/vmip.yaml
> +  staticIP: 10.255.255.254
it is required for kustomization. this IP will be replaced with IP address from module config subnet.

2024-08-26 21:37 UTC, hardcoretime commented on tests/e2e/config/config.go
> +	CustomSubnet            string           `yaml:"customSubnet"`
removed.

2024-08-26 21:39 UTC, hardcoretime commented on tests/e2e/config/config.go
> +	mc.Spec.Settings.VirtualMachineCIDRs = append(mc.Spec.Settings.VirtualMachineCIDRs, conf.CustomSubnet)
this operation removed.

2024-08-26 21:40 UTC, hardcoretime commented on tests/e2e/testdata/virtualization-resources/cvi/cvi-from-vi-alpine-http.yaml
> +      namespace: testcases
this required for kustomization.

2024-08-28 08:12 UTC, yaroslavborbat requested changes

2024-08-28 08:12 UTC, yaroslavborbat commented on tests/e2e/util_test.go
> +}
```suggestion
func FindUnassignedIP(subnets []string) (string, error) {
	var metas []metav1.ObjectMeta
	res := kubectl.List(kc.ResourceVMIPLease, kc.GetOptions{Output: "jsonpath='{.items[*].metadata}'"})
	if !res.WasSuccess() {
		return "", fmt.Errorf("failed to get vmipl: %s", res.StdErr())
	}
	if err := yamlv3.Unmarshal(res.StdOutBytes(), &metas); err != nil {
		return "", fmt.Errorf("failed to unmarshal vmipls metadata: %w", err)
	}
	reservedIPs := make(map[string]struct{}, len(metas))
	for _, m := range metas {
		ip := strings.ReplaceAll(strings.TrimPrefix(m.Name, "ip-"), "-", ".")
		reservedIPs[ip] = struct{}{}
	}
	for _, rawSubnet := range subnets {
		ip, subnet, err := net.ParseCIDR(rawSubnet)
		if err != nil {
			return "", fmt.Errorf("failed to parse subnet %s: %w", rawSubnet, err)
		}
		start := ipToInt(ip.To4())
		mask := net.IP(subnet.Mask).To4()
		broadcast := start | ^(ipToInt(mask))
		for uip := broadcast - 1; uip > start+1; uip-- {
			ip := intToIP(uip).String()
			if _, found := reservedIPs[ip]; found {
				continue
			}
			return ip, nil
		}
	}
	return "", fmt.Errorf("error: cannot find unassigned IP address")
}
```

I I didn't test suggestion func

2024-08-28 08:12 UTC, yaroslavborbat commented on tests/e2e/util_test.go
> +}
Are you sure about these functions? I don't fully understand how they work, leave comments

2024-08-28 08:16 UTC, yaroslavborbat commented on tests/e2e/util_test.go
> +}
although your way may be better in some cases

2024-08-28 18:21 UTC, yaroslavborbat submitted a review, later dismissed

2024-08-29 08:36 UTC, yaroslavborbat approved these changes

2024-08-29 09:04 UTC, merged