feat(vmop): add metrics
deckhouse/virtualization pull request #370
Opened 2024-09-12 13:16 UTC by yaroslavborbat

## Description
Add metrics for VMOP
`d8_virtualization_virtualmachineoperation_status_phase`
With base labels` ["name", "namespace", "uid"]`

## Why do we need it, and what problem does it solve?
we need more metrics

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [X] Changes were tested in the Kubernetes cluster manually.

2024-09-12 15:13 UTC, diafour commented on images/virtualization-artifact/pkg/monitoring/metrics/vmop/collector.go
> +		c.log.Error("Failed to iterate of VMOPs", logger.SlogErr(err))
```suggestion
		c.log.Error("Failed to iterate over VMOPs", logger.SlogErr(err))
```

2024-09-17 10:22 UTC, diafour submitted a review, later dismissed

2024-09-17 16:09 UTC, diafour submitted a review, later dismissed

2024-09-18 10:41 UTC, fl64 requested changes

2024-09-18 10:41 UTC, fl64 commented on monitoring/prometheus-rules/vmop.yaml
> +        severity_level: "6"
```suggestion
        severity_level: "9"
```

2024-09-18 10:41 UTC, fl64 commented on monitoring/prometheus-rules/vmop.yaml
> +        plk_grouped_by__d8_virtualization_vmop_health: "D8VirtualizationVmopHealth,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
```suggestion
        plk_create_group_if_not_exists__d8_virtualization_vmop_stuck_in_progress_state: "D8VirtualizationVmopStuckInProgressState,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        plk_grouped_by__d8_virtualization_vmop_stuck_in_progress_state: "D8VirtualizationVmopStuckInProgressState,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
```

2024-09-25 15:18 UTC, merged