fix(vm): change ip for running vm
deckhouse/virtualization pull request #374
Opened 2024-09-17 06:17 UTC by LopatinDmitr

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-09-24 21:05 UTC, yaroslavborbat requested changes

2024-09-24 21:05 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/vmip/internal/lifecycle_handler.go
> +	case vm != nil && vm.DeletionTimestamp == nil:
```suggestion
	case vm != nil && vm.GetDeletionTimestamp().IsZero():
```

2024-09-25 11:22 UTC, LopatinDmitr commented on images/virtualization-artifact/pkg/controller/vmip/internal/state/state.go
> +		vm, err := helper.FetchObject(ctx, vmKey, s.client, &virtv2.VirtualMachine{})
Fixed

2024-09-25 13:53 UTC, yaroslavborbat requested changes

2024-09-25 13:53 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/vmip/internal/state/state.go
> +		vm, err := helper.FetchObject(ctx, vmKey, s.client, &virtv2.VirtualMachine{})
not fixed

2024-09-25 13:55 UTC, yaroslavborbat approved these changes

2024-09-25 13:57 UTC, merged