feat(vmclass): add watcher for vmclass
deckhouse/virtualization pull request #389
Opened 2024-09-19 09:12 UTC by eofff

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-09-19 12:51 UTC, yaroslavborbat requested changes

2024-09-19 12:51 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/vm/internal/size_policy.go
> +	mgr := conditions.NewManager(changed.Status.Conditions)
don't use manager

2024-09-19 12:51 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/vm/internal/size_policy.go
> +	if update := addAllUnknown(changed, agentConditions...); update {
agentConditions?

2024-09-19 12:51 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/vm/internal/size_policy.go
> +	changed.Status.Conditions = mgr.Generate()
```suggestion
	conditions.SetCondition(cb, &changed.Status.Conditions)
```

2024-09-19 12:51 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/vm/vm_reconciler.go
> +				log.Error(err.Error())
add more context and use logger.SlogErr attr

2024-09-19 12:51 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/vm/vm_reconciler.go
> +				return !reflect.DeepEqual(oldVMC, newVMC)
compare resource spec. Not all

2024-09-19 12:52 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/vm/internal/size_policy.go
> +	mgr := conditions.NewManager(changed.Status.Conditions)
delete it

2024-09-19 13:46 UTC, yaroslavborbat approved these changes

2024-09-19 13:55 UTC, yaroslavborbat submitted a review, later dismissed

2024-09-19 15:05 UTC, Isteb4k requested changes

2024-09-19 15:05 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vm/internal/size_policy.go
> +		cb.Message("").
No need to call Message(""), empty string is already there

2024-09-19 15:05 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vm/internal/size_policy.go
> +		cb.Message(err.Error()).
The first letter in the condition must be uppercase, and the message must end with a dot.

2024-09-20 08:00 UTC, Isteb4k requested changes

2024-09-20 08:00 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vm/internal/watcher/vmclass_watcher.go
> +			CreateFunc: func(e event.CreateEvent) bool { return false },
Are you sure there's no need to watch create and update events? What if a vmclass was missed but has now been created?

2024-09-24 09:29 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/vm/internal/validators/sizing_policy_validator.go
> +	return nil, v.service.CheckVMMatchedSizePolicy(vm, vmClass)
don't repeat yourself

2024-09-25 08:13 UTC, yaroslavborbat requested changes

2024-09-25 08:13 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/vm/internal/size_policy.go
> +	if err != nil && !errors.IsNotFound(err) {
helper.FetchObject is used by the s.Class method. No need to handle "not found" error

2024-09-25 08:53 UTC, Isteb4k requested changes

2024-09-25 08:53 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vm/internal/size_policy.go
> +	if isDeletion(current) {
The condition is not set here when you return

2024-09-25 12:07 UTC, Isteb4k approved these changes

2024-09-25 12:19 UTC, yaroslavborbat requested changes

2024-09-25 12:19 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/vm/internal/size_policy.go
> +		)
```suggestion
		return reconcile.Result{}, err
```

2024-09-25 12:26 UTC, yaroslavborbat approved these changes

2024-09-25 12:34 UTC, yaroslavborbat approved these changes

2024-09-25 14:39 UTC, merged