test(api): add e2e disk attachment test
deckhouse/virtualization pull request #395
Opened 2024-09-23 00:23 UTC by hardcoretime

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-09-24 09:46 UTC, yaroslavborbat requested changes

2024-09-24 09:46 UTC, yaroslavborbat commented on tests/e2e/resources/resources.go
> +	ApiVersion string          `yaml:"apiVersion"`
use our api package

2024-09-24 09:46 UTC, yaroslavborbat commented on tests/e2e/util_test.go
> +func GetManifest[T Resource](manifest string) (*T, error) {
[T client.Object]

2024-09-25 09:01 UTC, Isteb4k requested changes

2024-09-25 09:01 UTC, Isteb4k commented on tests/e2e/vm_migration_test.go
> +	err := WriteYamlObject(filePath, &vmim)
Already pointer

2024-09-25 10:55 UTC, Isteb4k approved these changes

2024-09-25 12:44 UTC, yaroslavborbat approved these changes

2024-09-25 12:49 UTC, merged