feat(vmop): first implementation
deckhouse/virtualization pull request #4
Opened 2024-02-06 07:41 UTC by yaroslavborbat

## Description
 Implementation resource VirtualMachineOperation. 
 The VirtualMachineOperation custom resource allows for declarative management of a working virtual machine. It enables actions such as stopping, starting, and restarting the virtual machine.

## Why do we need it, and what problem does it solve?
The VirtualMachineOperation resource is needed to provide a high-level abstraction for managing virtual machines. It solves the problem of efficiently and easily controlling the state of virtual machines through a declarative approach, rather than relying on manual, time-consuming operations.

## What is the expected result?
VirtualMachineOperation is an immutable resource. After deployment, it can have 4 phases of status: Completed, Failed, InProgress, Pending.

2024-02-06 09:02 UTC, Isteb4k requested changes

2024-02-09 08:46 UTC, Isteb4k approved these changes

2024-02-09 08:46 UTC, Isteb4k commented on images/virtualization-controller/pkg/common/kvvm/util.go
> +		return fmt.Errorf("kvvm must not be empty")
**kvvmi** must not be empty

2024-02-09 09:39 UTC, diafour commented on images/virtualization-controller/pkg/controller/vmop/vmop_webhook.go
> +	err := fmt.Errorf("misconfigured webhook rools: delete operation not implemented")
```suggestion
	err := fmt.Errorf("misconfigured webhook rules: delete operation not implemented")
```

2024-02-09 09:40 UTC, diafour commented on images/virtualization-controller/pkg/controller/vmop/vmop_webhook.go
> +	err := fmt.Errorf("misconfigured webhook rools: delete operation not implemented")
```suggestion
	err := fmt.Errorf("misconfigured webhook rules: delete operation not implemented")
```

2024-02-09 09:41 UTC, diafour commented on images/virtualization-controller/pkg/controller/vmop/vmop_reconciler_state.go
> +		return nil, fmt.Errorf("VM %s not found", state.VMOP.Current().Spec.VirtualMachineName)
```suggestion
		return nil, fmt.Errorf("KVVM %s not found", state.VMOP.Current().Spec.VirtualMachineName)
```

2024-02-09 09:41 UTC, diafour commented on images/virtualization-controller/pkg/controller/vmop/vmop_reconciler_state.go
> +		return nil, fmt.Errorf("VM %s not found", state.VMOP.Current().Spec.VirtualMachineName)
```suggestion
		return nil, fmt.Errorf("KVVMI %s not found", state.VMOP.Current().Spec.VirtualMachineName)
```

2024-02-09 09:44 UTC, diafour commented on images/virtualization-controller/pkg/controller/vmop/vmop_reconciler.go
> +		return fmt.Errorf("unexpected opearation %q. %w", operationSpec.Type, common.ErrUnknownValue)
```suggestion
		return fmt.Errorf("unexpected operation %q. %w", operationSpec.Type, common.ErrUnknownValue)
```

2024-02-09 09:46 UTC, diafour commented on images/virtualization-controller/pkg/common/kvvm/util.go
> +	return cli.Delete(ctx, pod, opts)
Should handle IsNotFound error

2024-02-09 11:38 UTC, merged