test(performance): status-access-vms
deckhouse/virtualization pull request #44
Opened 2024-04-04 09:00 UTC by universal-itengineer

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-04-04 15:58 UTC, fl64 commented
I have a suggestion to add a taskfile with the following tasks:
- run-ansible
- run-tank

2024-04-04 15:58 UTC, fl64 requested changes

2024-04-04 15:58 UTC, fl64 commented on tests/performance/status-access-vms/ansible/run.sh
> +function prepaer_ssh_key {
```suggestion
function prepare_ssh_key {
```

2024-04-04 15:58 UTC, fl64 commented on tests/performance/status-access-vms/ansible/run.sh
> +    prepaer_ssh_key
```suggestion
    prepare_ssh_key
```

2024-04-04 15:58 UTC, fl64 commented on tests/performance/status-access-vms/ansible/ansible.cfg
> +collections_path=$PWD/collections
Do we need this?

2024-04-04 15:58 UTC, fl64 commented on tests/performance/status-access-vms/ansible/ansible.cfg
> +deprecation_warnings=Talse
```suggestion
deprecation_warnings=false
```

2024-04-04 15:58 UTC, fl64 commented on tests/performance/status-access-vms/ansible/ansible.cfg
> +bin_ansible_callbacks=True
```suggestion
bin_ansible_callbacks=true
```

2024-04-04 15:58 UTC, fl64 commented on tests/performance/status-access-vms/ansible/ansible.cfg
> +host_key_checking=False
Please replace all booleans with lowercase letters

2024-04-04 15:58 UTC, fl64 commented on tests/performance/status-access-vms/ansible/run.sh
> +        echo "    ${vm_name}.${NAMESPACE}:" >> $inventory_file
why not VM_NAME?

2024-04-04 15:58 UTC, fl64 commented on tests/performance/status-access-vms/sshkeys/id_ed
> +-----BEGIN OPENSSH PRIVATE KEY-----
Do we really need to keep it here?

2024-04-16 08:02 UTC, diafour commented on tests/performance/status-access-vms/ansible/run.sh
> +        echo -e "---\n"
```suggestion
        echo "---"
```

2024-05-08 14:25 UTC, diafour approved these changes

2024-06-05 11:34 UTC, fl64 approved these changes

2024-06-05 14:15 UTC, merged