feat(vd): block expanding vd when storageclass not ready
deckhouse/virtualization pull request #466
Opened 2024-10-22 12:47 UTC by eofff

## Description
Should block expanding pvc size when StorageClass not ready.

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-10-28 08:00 UTC, LopatinDmitr commented on images/virtualization-artifact/pkg/controller/vd/internal/validators/pvc_size_validator.go
> +		return nil, errors.New("can not expand spec.persistentVolumeClaim.size because storage class not ready")
May be use `fmt.Errorf(` instead `errors.New(`

2024-10-30 06:51 UTC, yaroslavborbat submitted a review, later dismissed

2024-11-01 16:18 UTC, Isteb4k requested changes

2024-11-01 16:18 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vd/internal/validators/pvc_size_validator.go
> +		return nil, fmt.Errorf("can not expand spec.persistentVolumeClaim.size because `StorageClass` of `VirtualDisk` not ready")
cannot
is not ready

2024-11-01 16:19 UTC, Isteb4k requested changes

2024-11-01 16:19 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vd/internal/validators/pvc_size_validator.go
> +		return nil, fmt.Errorf("can not expand spec.persistentVolumeClaim.size because `StorageClass` of `VirtualDisk` not ready")
Why fmt.Errorf ? There are no format options to use

2024-11-15 12:20 UTC, closed without merging