chore(core): mitigation cve dvcr-importer and vm-route-forge
deckhouse/virtualization pull request #506
Opened 2024-11-06 19:51 UTC by universal-itengineer

## Description

Fixing vulnerabilities in dvcr-importer and vm-route-forge
## Why do we need it, and what problem does it solve?

Vulnerability mitigation:
CVE-2024-28180
CVE-2024-47825
## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [X] Changes were tested in the Kubernetes cluster manually.

2024-11-06 19:55 UTC, yaroslavborbat submitted a review, later dismissed

2024-11-07 10:24 UTC, Isteb4k requested changes

2024-11-07 11:10 UTC, yaroslavborbat commented on images/dvcr-artifact/pkg/monitoring/progress.go
> +func NewProgress(importProgress *prometheus.GaugeVec, lvs ...string) *ImportProgress {
label values. Its a default naming in prometheus

2024-11-07 11:38 UTC, yaroslavborbat commented on images/dvcr-artifact/pkg/importer/importer.go
> +		durCollector.Collect())
maybe the linter did it

2024-11-07 11:44 UTC, yaroslavborbat commented on images/dvcr-artifact/pkg/monitoring/progress.go
> +func NewProgress(importProgress *prometheus.GaugeVec, lvs ...string) *ImportProgress {
renamed

2024-11-07 11:45 UTC, yaroslavborbat approved these changes

2024-11-07 12:05 UTC, Isteb4k submitted a review, later dismissed

2024-11-08 11:00 UTC, universal-itengineer commented on images/dvcr-artifact/go.mod
> +	// kubevirt.io/containerized-data-importer-api v1.57.0-alpha1
```suggestion
```

2024-11-08 14:49 UTC, diafour submitted a review, later dismissed

2024-11-08 15:08 UTC, Isteb4k approved these changes

2024-11-08 17:07 UTC, diafour approved these changes

2024-11-08 19:11 UTC, merged