feat: added emulation of virtual machine movements
deckhouse/virtualization pull request #54
Opened 2024-04-09 15:56 UTC by Isteb4k

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-04-10 13:39 UTC, yaroslavborbat approved these changes

2024-04-10 13:47 UTC, yaroslavborbat requested changes

2024-04-10 13:47 UTC, yaroslavborbat commented on tests/performance/shatal/internal/shatal/drainer.go
> +			cmd := exec.CommandContext(context.Background(), "kubectl", "drain", node, "--ignore-daemonsets", "--delete-emptydir-data")
conflicts with kubeconfigBase64 in config

2024-04-10 13:47 UTC, yaroslavborbat commented on tests/performance/shatal/internal/shatal/drainer.go
> +			cmd = exec.CommandContext(context.Background(), "kubectl", "uncordon", node)
conflicts with kubeconfigBase64 in config

2024-04-10 14:09 UTC, universal-itengineer commented on tests/performance/shatal/Taskfile.yaml
> +    desc: "Run emulation of virtual machine movements"
```suggestion
    desc: "Run of virtual machine migrations after node drain"
```

2024-04-10 16:24 UTC, diafour commented on tests/performance/templates/vms.yaml
> +    {{- end }}
Comment this block please. It is not clear why Automatic/Manual should depend on VM number.

2024-04-10 16:31 UTC, diafour commented on tests/performance/shatal/internal/shatal/modifier.go
> +		vm.Spec.CPU.CoreFraction = "10%"
Move them to constants

2024-04-10 16:38 UTC, diafour commented on tests/performance/shatal/internal/shatal/modifier.go
> +	err := s.api.UpdateVM(ctx, vm)
I have a feeling that Patch is better, as Update may lead to error "unable to update ... the object has been modified; please apply your changes to the latest version and try again".

2024-06-05 05:53 UTC, universal-itengineer commented on tests/performance/shatal/README.md
> +task run
```suggestion
KUBECONFIG=$(cat ~/.kube/config | base64 -w 0)
KUBECONFIG_BASE64=$KUBECONFIG task shatal:run
```

2024-06-05 05:55 UTC, universal-itengineer approved these changes

2024-06-05 11:39 UTC, yaroslavborbat approved these changes

2024-06-05 12:32 UTC, merged