fix(vm): split sync kvvm and power state
deckhouse/virtualization pull request #558
Opened 2024-12-05 21:50 UTC by LopatinDmitr

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-12-16 07:30 UTC, yaroslavborbat requested changes

2024-12-16 07:30 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/vm/internal/sync_power_state.go
> +		}
no needed

2024-12-16 07:30 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/vm/internal/sync_power_state.go
> +		err = h.ensureRunStrategy(ctx, kvvm, virtv1.RunStrategyManual)
we should always set manual strategy for all runPolicy.

2024-12-16 20:56 UTC, LopatinDmitr commented on images/virtualization-artifact/pkg/controller/vm/internal/sync_power_state.go
> +		}
Fixed.

2024-12-17 07:03 UTC, yaroslavborbat submitted a review, later dismissed

2024-12-17 10:24 UTC, yaroslavborbat approved these changes

2024-12-17 10:24 UTC, merged