feat: add webhook for validating module config virtualization
deckhouse/virtualization pull request #571
Opened 2024-12-12 09:35 UTC by yaroslavborbat

## Description
Add a webhook for ModuleConfig Virtualization
It is forbidden to delete used CIDRs

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [X] Changes were tested in the Kubernetes cluster manually.

2024-12-17 11:10 UTC, Isteb4k approved these changes

2024-12-17 17:17 UTC, diafour commented on images/virtualization-artifact/pkg/controller/moduleconfig/util.go
> +					return fmt.Errorf("error parsing node IP: %w", err)
It should not be the "stop everything" error, this validator checks if nodes IPs are overlapped with CIDRs in ModuleConfig. If IP is not parsed it is ok.

2024-12-17 17:19 UTC, diafour commented on images/virtualization-artifact/pkg/controller/moduleconfig/util.go
> +						return fmt.Errorf("node address %s may overlap with subnet %s", ip, prefix)
```suggestion
						return fmt.Errorf("subnet %s is invalid, it should not contains addresses assigned to nodes: got node %s with IP %s", prefix, node.GetName(), ip)
```

2024-12-17 17:23 UTC, diafour commented on images/virtualization-artifact/pkg/controller/moduleconfig/reduce_cidrs_validator.go
> +				return nil, fmt.Errorf("CIDR %q is in use by one or more IP addresses", CIDR)
```suggestion
				return nil, fmt.Errorf("CIDR %q can't be removed: VirtualMachineIPAddressLease/%s holds IP address from this network", CIDR, lease.GetName())
```

2024-12-17 17:26 UTC, diafour commented on images/virtualization-artifact/pkg/controller/moduleconfig/reduce_cidrs_validator.go
> +const virtualMachineCIDRs = "virtualMachineCIDRs"
This const is not used in this file. Move it to utils.go or move parseCIDRs in this file.

2024-12-17 17:32 UTC, diafour commented on images/virtualization-artifact/pkg/controller/moduleconfig/reduce_cidrs_validator.go
> +type reduceCIDRsValidator struct {
Thoughts on naming. This validation is not about "reducing" CIDRs items, it is about "removing" used CIDRs. I think of this case: new CIDR added and used CIDR is removed, no changes in CIDRs length, nothing reduced, but _removed_ CIDR should be validated.

2024-12-17 18:38 UTC, yaroslavborbat commented on hooks/module_config_validator.py
> +                    "queue": f"/modules/{self.module_name}/{self.SNAPSHOT_NAME}",
Yes, but in other hooks we have the same names.

2024-12-20 08:53 UTC, diafour commented on images/virtualization-artifact/pkg/controller/moduleconfig/util.go
> +					continue
```suggestion
					// No way to detect if invalid address is in excludedPrefixes, just ignore the error and move on.
					continue
```

2024-12-20 08:53 UTC, diafour commented on images/virtualization-artifact/pkg/controller/moduleconfig/reduce_cidrs_validator.go
> +type removeCIDRsValidator struct {
Please, rename the file.

2024-12-23 09:40 UTC, diafour submitted a review, later dismissed

2025-01-09 15:45 UTC, Isteb4k requested changes

2025-01-09 15:52 UTC, Isteb4k requested changes

2025-01-09 15:52 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/moduleconfig/util.go
> +			return nil, fmt.Errorf("failed to convert value %v to a string", v)
Is this internal error? Or user set wrong value to mc

2025-01-10 08:02 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/moduleconfig/remove_cidrs_validator.go
> +			return nil, fmt.Errorf("failed to parse lease ip: %w", err)
I don't quite understand why errors in webhooks are categorized as internal and non-internal. Regardless of the type of error, we should surface it to the user and halt further execution. That said, I have added logging for all errors at a lower level. See validator/validator.go

2025-01-10 08:04 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/moduleconfig/util.go
> +			return nil, fmt.Errorf("failed to convert value %v to a string", v)
This error occurs because the user provided an incorrect value to mc. However, this scenario should be impossible since we have validation in place at the OpenAPI level.

2025-01-10 08:06 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/moduleconfig/cidrs_validator.go
> +		return fmt.Errorf("error listing nodes: %w", err)
The user doesn't need to do anything in this case. They can try resending the request. I believe this error should be returned to provide better context for the user, rather than being masked as just an internal error.

2025-01-10 08:09 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/moduleconfig/util.go
> +				return fmt.Errorf("overlapping CIDRs %v and %v", prefixes[i], prefixes[j])
improve msg

2025-01-10 08:11 UTC, yaroslavborbat commented on images/virtualization-artifact/pkg/controller/moduleconfig/util.go
> +						return fmt.Errorf("subnet %s is invalid, it should not contains addresses assigned to nodes: got node %s with IP %s", prefix, node.GetName(), ip)
fixed

2025-01-10 08:56 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/moduleconfig/cidrs_validator.go
> +		return fmt.Errorf("error listing nodes: %w", err)
Please add more context for user, what the problem

2025-01-13 13:10 UTC, Isteb4k requested changes

2025-01-13 13:10 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/moduleconfig/util.go
> +			return nil, fmt.Errorf("failed to convert value %v to a string", v)
May be add "please report a bug" here?
Or add the error log here
Or even both are better

2025-01-13 13:10 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/moduleconfig/util.go
> +			return nil, fmt.Errorf("failed to parse CIDR %s: %w", CIDR, err)
It's important to ask user report about our bug here
And log the error
Please check other errors as well: The user must either understand that he screwed up somewhere, or understand that the error occurred on our side and he should to either try again later, or report the bug.

2025-01-13 13:12 UTC, Isteb4k requested changes

2025-01-13 13:12 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/moduleconfig/remove_cidrs_validator.go
> +		return nil, fmt.Errorf("failed to list VirtualMachineIPAddressLeases: %w", err)
It's important to ask user report about our bug here
And log the error
Please check other errors as well: The user must either understand that he screwed up somewhere, or understand that the error occurred on our side and he should to either try again later, or report the bug.

2025-01-15 10:02 UTC, Isteb4k approved these changes

2025-01-15 10:02 UTC, merged