feat(vmclass): Add events about available nodes and sizing policies changed
deckhouse/virtualization pull request #606
Opened 2024-12-24 14:32 UTC by eofff

## Description
Using new events api.
Add event when list of available nodes changed.
Add event when sizing policies changed.

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-12-25 18:01 UTC, Isteb4k requested changes

2024-12-25 18:01 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vmclass/internal/discovery.go
> +func nodeNamesDiff(prev, current []string) (added, removed []string) {
Cover this fn with unit test please

2025-01-15 08:59 UTC, diafour commented on images/virtualization-artifact/pkg/controller/vmclass/internal/deletion.go
> +		Message("")
No need to add a separate condition "VMClassFree", vmclass is in a deletion state at this point, it will be deleted almost immediately after removing finalizers.

2025-01-22 07:48 UTC, Isteb4k requested changes

2025-01-22 07:48 UTC, Isteb4k commented on api/core/v1alpha2/events.go
> +	// ReasonVMClassSizingPoliciesWasChanged is event reason that VMClass sizing policies was changed.
were changed

2025-01-22 07:48 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vmclass/internal/validators/policy_changes_validator.go
> +		v.recorder.Event(newVMClass, corev1.EventTypeNormal, v1alpha2.ReasonVMClassSizingPoliciesWasChanged, "Sizing policies was changed")
were

2025-01-22 07:48 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vmclass/internal/deletion.go
>  		return reconcile.Result{RequeueAfter: 60 * time.Second}, nil
Why not subscribe to virtual machine deletion?

2025-01-22 07:48 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vmclass/internal/deletion.go
> +		Message("")
+1

2025-01-22 07:48 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vmclass/internal/discovery.go
> +	for _, n := range prev {
n usually means a number, but I suppose not in this context.

2025-01-22 07:48 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vmclass/internal/discovery_test.go
> +var _ = Describe("DiscoveryHandler Run", func() {
DiscoveryHandler doesn't have method Run

2025-01-27 14:43 UTC, Isteb4k commented on api/core/v1alpha2/events.go
> +	// ReasonVMClassSizingPoliciesWasChanged is event reason that VMClass sizing policies was changed.
It's still relevant. Check in other places too.

2025-01-27 15:08 UTC, Isteb4k requested changes

2025-01-27 15:08 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vmclass/internal/deletion.go
> +		msg := fmt.Sprintf("VirtualMachineClass cannot be deleted, there are VMs that use it. %q", vmNamespacedNames)
"VirtualMachineClass cannot be deleted, there are virtual machines that use it: %s." 

The names of virtual machines must be separated by commas, and a period must be placed at the end

2025-01-27 15:08 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vmclass/internal/deletion.go
>  		return reconcile.Result{RequeueAfter: 60 * time.Second}, nil
It's still relevant.

2025-01-27 15:08 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vmclass/internal/watcher/vm_watcher.go
> +				return nil
Dont ignore errors, never
Use FetchObject

2025-01-31 08:34 UTC, Isteb4k requested changes

2025-01-31 08:34 UTC, Isteb4k commented on api/core/v1alpha2/events.go
> +	ReasonVMClassAvailableNodesWasUpdated = "AvailableNodesWasUpdated"
Nodes were updated

2025-01-31 08:34 UTC, Isteb4k commented on api/core/v1alpha2/vmclasscondition/condition.go
> +	// ReasonVMClassFree is event reason that VMClass not used by virtual machine.
is not used

Use a translator to avoid mistakes in English

2025-02-04 13:52 UTC, Isteb4k requested changes

2025-02-04 13:52 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vmclass/internal/deletion.go
> +		msg := fmt.Sprintf("VirtualMachineClass cannot be deleted, there are VMs that use it %s.", strings.Join(vmNamespacedNames, ", "))
VirtualMachineClass cannot be deleted, there are VMs that use it: %s.
VirtualMachineClass cannot be deleted, there is VM that use it: %s.

2025-02-04 13:52 UTC, Isteb4k commented on images/virtualization-artifact/pkg/controller/vmclass/internal/deletion.go
> +		msg := fmt.Sprintf("VirtualMachineClass cannot be deleted, there are VMs that use it %s.", strings.Join(vmNamespacedNames, ", "))
Give different messages depending on whether there is one VM or multiple. And add a colon before listing the VMs.

2025-02-05 08:51 UTC, Isteb4k approved these changes

2025-02-05 08:58 UTC, merged